---
After: framework
---
Director:
  rules:
    "": HomeController
    "add-ons": AddonsController
    "vendors": VendorsController
    "authors": AuthorsController
    "tags": TagsController
    "submit": SubmitAddonController
    "addonSort": AjaxController
    'api/rating': RatingApiController
    'api/ratings': RatingsApiController
    'api/supported-addons': SupportedAddonsApiController
    'api/addons': AddonsApiController
